### PR TITLE
Create soka.js

### PR DESCRIPTION
**Pull request by animeforreal**
xvxfv

### CODE REVIEW

**Review by animeforreal — COMMENTED** [review]
ohhh

**Comment by djohts** [comment]
sus

**Review by animeforreal — COMMENTED** [review]
lmao

**Comment by animeforreal** [comment]
> lmao

aaa

**Review by animeforreal — COMMENTED** [review]
nani

**Comment by animeforreal** [comment]
soka

**Comment by AngeloCore** [comment]
Poka

**Comment by animeforreal** [comment]
Nani the h

**Comment by animeforreal** [comment]
wow

**Comment by LegendaryEmoji** [comment]
no u

**Comment by animeforreal** [comment]
working

**Comment by animeforreal** [comment]
test

**Comment by LegendaryEmoji** [comment]
woking wot

**Comment by LegendaryEmoji** [comment]
**let** ### me _use_ 

> some crazy designing

```js
eval("process.exit(1)")
```

[wot da heck](https://github.com/animeforreal/Power-of-anime/pull/5)

- dd

1. ddos

- [ f] lol

@animeforreal #1

**Comment by animeforreal** [comment]
this is Elon musk speaking :D

**Comment by animeforreal** [comment]
fishy

**Comment by animeforreal** [comment]
whats up

**Comment by animeforreal** [comment]
what

**Comment by animeforreal** [comment]
i am testing bro :D

**Comment by animeforreal** [comment]
Noooo

**Comment by LegendaryEmoji** [comment]
my pp hard

**Comment by animeforreal** [comment]
make it soft when

**Comment by LegendaryEmoji** [comment]
when i buy lotion

**Comment by animeforreal** [comment]
do Meditation then see effects

**Comment by LegendaryEmoji** [comment]
thanks for advice senpai

**Comment by animeforreal** [comment]
No problem, let me know how it goes

**Comment by LegendaryEmoji** [comment]
sure 👌

**Comment by animeforreal** [comment]
meow

**Comment by LegendaryEmoji** [comment]
bao bao

**Pull request closed without merging**
